apiVersion: v1

kind: Pod

metadata:
  name: worker-app-prod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: worker-app
      #image: dockersamples/examplevotingapp_worker
      image: mathewakhil/voting-app:workerapp 


